### ISSUE TITLE
"make check-versions" fails with case-sensitive file systems

### ISSUE THREAD

**Issue by khinsen** [haroldthimbleby/Software-Enginering-Boards#1]
On a standard Linux system, `make check-versions` fails when testing `bibtex` due to a typo in `makefile`.

The line
```
	@$(call checkVersion,Bibtex,BibTeX 0.99d (TeX Live 2021),)
```
should read
```
	@$(call checkVersion,bibtex,BibTeX 0.99d (TeX Live 2021),)
```
i.e. `bibtex` in all lower-case.

**Comment by haroldthimbleby** [comment]
That's very helpful; thanks. On Darwin (which I'm using) the disk format
can be set, as I have done, so case doesn't matter -- and so you don't
notice the problem :-)

Anyways, now fixed.

best,

Harold
---
Prof. Harold Thimbleby PhD FLSW FRCPE HonFRSA HonFRCP
See Change Fellow in Digital Health
Fix IT - see https://tinyurl.com/3hkrazdp
Web site - http://harold.thimbleby.net

**Comment by haroldthimbleby** [comment]
Hi Konrad

Thanks so much for those observations/suggestions; they've led to many
minor improvements in the scripts as well. I really appreciate your
attention to detail. (I put your name in the acknowledgements in the
previous revision.)

(The text of the paper and supplementary material hasn't changed, I've only
made mods to the makefile, etc, to make things smoother - well, more
honestly, as you noticed, to make things work!)

best,

Harold
---
Prof. Harold Thimbleby PhD FLSW FRCPE HonFRSA HonFRCP
See Change Fellow in Digital Health
Fix IT - see https://tinyurl.com/3hkrazdp
Web site - http://harold.thimbleby.net

**Comment by khinsen** [comment]
Harold,

thanks for fixing these issues! My goal is to get this running to the end.

I am particularly interested in exploring your code because I am currently working on a MOOC that explains the techniques for reproducible computations. Full automation is one important point, and `make` is one of the two tools we use to illustrate how this can be done (the other one is `snakemake`).

BTW, you might be interested in [Maneage](https://maneage.org/), a framework for automation that is similar to your approach in many ways. The main difference is that it doesn't merely record versions of all software packages, but actually installs a specific version fixed in the project's definition. Better reproducibility, at the price of lengthy compilations before the first run.

Best,
  Konrad.

**Comment by khinsen** [comment]
Also interesting: https://tinyurl.com/tuto-techno

Seen yesterday in a thesis defense. Fully automated high-performance computing!

**Comment by haroldthimbleby** [comment]
Fascinating ideas, ripe for generalisingI had two background thoughts:We are bad at describing new ideas abstractly - a lot of it is concrete “how it works” from which reader has to be the scientist objectifying and inventing the categories / principles Have you seen my relit paper - https://www.sciencedirect.com/science/article/pii/S0167642317302952From Harold's iPhoneThe Patron Saint of copying people into emails is St Francis
 of a CC.   Too brief? Here's why: https://medium.com/virtual-teams-for-systemic-change/the-email-charter-an-idea-worth-spreading-688b8940f892On 23 Feb 2023, at 15:20, Konrad Hinsen ***@***.***> wrote:﻿
Also interesting: https://tinyurl.com/tuto-techno
Seen yesterday in a thesis defense. Fully automated high-performance computing!

**Comment by khinsen** [comment]
relit looks like an interesting variant on the many similar tools already out there! Looks like a good choice for those who are proficient at LaTeX already.
