### ISSUE TITLE
"make all" fails because of a missing directory

### ISSUE THREAD

**Issue by khinsen** [haroldthimbleby/Software-Enginering-Boards#2]
`make all` fails with the error message (extract from the full output):
```
cd models-data-fitting; run
/gnu/store/4y5m9lb8k3qkb1y9m02sw9w9a6hacd16-bash-minimal-5.1.8/bin/sh: line 1: cd: models-data-fitting: No such file or directory
```
There is indeed no directory `models-data-fitting`.

**Comment by haroldthimbleby** [comment]
I'm nearly done fixing these embarrassing typos!

It comes, of course, from making changes to file names to make everything
clearer!

best,

Harold
---
Prof. Harold Thimbleby PhD FLSW FRCPE HonFRSA HonFRCP
See Change Fellow in Digital Health
Fix IT - see https://tinyurl.com/3hkrazdp
Web site - http://harold.thimbleby.net
