### ISSUE TITLE
models/run fails

### ISSUE THREAD

**Issue by khinsen** [haroldthimbleby/Software-Enginering-Boards#4]
The script `run` in directory `models` fails:

```
./run: line 6: .: scan: file not found
```

**Comment by haroldthimbleby** [comment]
Mea culpa! Will fix asap; its in progs/scanFrom Harold's iPhoneThe Patron Saint of copying people into emails is St Francis
 of a CC.   Too brief? Here's why: https://medium.com/virtual-teams-for-systemic-change/the-email-charter-an-idea-worth-spreading-688b8940f892On 20 Feb 2023, at 17:58, Konrad Hinsen ***@***.***> wrote:﻿
The script run in directory models fails:
./run: line 6: .: scan: file not found

**Comment by khinsen** [comment]
The following patch seems to fix this issue:
```
@@ -3,7 +3,7 @@ rm -rf "git-covid-sim"
 git clone "http://github.com/mrc-ide/covid-sim" "git-covid-sim"
 
 . ../generated/allGitRepos.sh
-. scan > ../generated/repos.tex
+./scan > ../generated/repos.tex
 
 # check that PostoperativeOutcomes_RiskNet README.md has not been updated
 # otherwise sections in the paper need fixing!
```
