### ISSUE TITLE
Image file generated/basic.pdf has no bounding box

### ISSUE THREAD

**Issue by khinsen** [haroldthimbleby/Software-Enginering-Boards#7]
LaTeX says:
```
LaTeX Error: Cannot determine size of graphic in generated/basic.pdf (no BoundingBox)
```
and stops processing `paper-seb-supplementary-material.tex`

**Comment by haroldthimbleby** [comment]
This fix to paper-seb-supplementary-material.tex seems to fix it (already pushed)

\PassOptionsToPackage{dvipdfmx}{graphicx}

If so, it's very likely a byte/multibyte portability issue - but it worked for me before, and still works, so I don't  know! Please try re-rerunning and see what happens. If all fails, I can easily convert to JPGs etc.

**Comment by khinsen** [comment]
I still get the same error message. It's actually worse: there are two error messages:
```
LaTeX Warning: File `generated/basic.pdf' not found on input line 500.

! LaTeX Error: Cannot determine size of graphic in generated/basic.pdf (no Boun
dingBox).
```

It's weird to see "file not found" for a file that definitely exists! And I have the same problem with other PDF includes under `generated`.

**Comment by haroldthimbleby** [comment]
Doh! I'll change the code to generate JPG, and "we" (both of us) will try
that? Give me a moment...

I do appreciate your perseverance on a different system. Gosh, you'd have
thought the folk in charge of Unix and Mathematica and .. and .. and  ..
would have sorted these issues out a decade ago, right? Hah.

best,

Harold
---
Prof. Harold Thimbleby PhD FLSW FRCPE HonFRSA HonFRCP
See Change Fellow in Digital Health
Fix IT - see https://tinyurl.com/3hkrazdp
Web site - http://harold.thimbleby.net

**Comment by haroldthimbleby** [comment]
Now works my end. Let me know how you get on! And more importantly - have a
good weekend.

best,

Harold
---
Prof. Harold Thimbleby PhD FLSW FRCPE HonFRSA HonFRCP
See Change Fellow in Digital Health
Fix IT - see https://tinyurl.com/3hkrazdp
Web site - http://harold.thimbleby.net

**Comment by khinsen** [comment]
Still the same problem:
```
LaTeX Warning: File `generated/basic.jpg' not found on input line 494.
```
And yet, the file exists, and I can open it with an image viewer!

**Comment by haroldthimbleby** [comment]
Hmm

It sounds like a problem your end :-) though if I can fix something here,
love to know what!

Where are you running Latex? Obviously generated/ should be a directory in
the place where you're running Latex as the image uses a relative filename.

What is your Latex dvi...etc driver?

What are the permissions of your generated/ directory?

% ls -ld generated

drwxr-xr-x  33 harold  staff  1056 Feb 27 13:20 generated

PS I added WolframScript into the version checking bit of the makefile
See
https://reference.wolfram.com/language/workflow/InstallWolframScript.html
for details of getting it (if you want it!)


best,

Harold
---
Prof. Harold Thimbleby PhD FLSW FRCPE HonFRSA HonFRCP
See Change Fellow in Digital Health
Fix IT - see https://tinyurl.com/3hkrazdp
Web site - http://harold.thimbleby.net

**Comment by khinsen** [comment]
Yes, this could well be a problem on my end. I ran LaTeX under `strace`, which shows that the access to the file succeeds. But then, LaTeX accesses potentially related files (`generated/basic.jpg.tex`, `generated/basic.jpg.eps` and others), and those accesses fail. All permissions are fine. This is weird!

**Comment by haroldthimbleby** [comment]
Fun! I'd be tempted

a) put an image file I know works in the directory, also under strace to
compare
b) do

ls -al

c) Move the file to another directory (eg the parent) and edit the
\includegraphics accordingly. Is it where it is, or what it is?
best,

Harold
---
Prof. Harold Thimbleby PhD FLSW FRCPE HonFRSA HonFRCP
See Change Fellow in Digital Health
Fix IT - see https://tinyurl.com/3hkrazdp
Web site - http://harold.thimbleby.net

**Comment by haroldthimbleby** [comment]
I tried this: perhaps it's another case or byte coding problem?

At my end, the image file names are all 8 bit ASCII coded as follows (also
named, same case, in ASCII in the includegraphics in the respective .tex
files)

% cd generated

% ls *jpg | od -t a

0000000    b   a   s   i   c   .   j   p   g  nl   e   x   c   e   l   .

0000020    j   p   g  nl   i   m   p   o   r   t   .   j   p   g  nl   m

0000040    a   t   h   e   m   a   t   i   c   a   p   l   o   t   .   j

0000060    p   g  nl   n   o   t   e   b   o   o   k   .   j   p   g  nl

0000100


best,

Harold
---
Prof. Harold Thimbleby PhD FLSW FRCPE HonFRSA HonFRCP
See Change Fellow in Digital Health
Fix IT - see https://tinyurl.com/3hkrazdp
Web site - http://harold.thimbleby.net

**Comment by khinsen** [comment]
Update: this happens with all image files I tried. Including image files from my presentations, all done with LaTeX and Beamer. But I use `pdflatex` for those, not plain `latex`. And with `pdflatex`, I can process you file as well (almost, but the image issues are gone).

So this looks like some issue with different LaTeX engines, possible in combination with the "graphics" package that contains code specific to different engines.

**Comment by haroldthimbleby** [comment]
Wow. Even with jpegs? They're a fixed, much simpler format than PDF (which
conceals many driver problems...). Do you want to try PNG? (works this
end:-)

best,

Harold
---
Prof. Harold Thimbleby PhD FLSW FRCPE HonFRSA HonFRCP
See Change Fellow in Digital Health
Fix IT - see https://tinyurl.com/3hkrazdp
Web site - http://harold.thimbleby.net

**Comment by khinsen** [comment]
Even JPEG, and also PNG.

**Comment by haroldthimbleby** [comment]
I've no idea but my homework seems to suggest you try EPS. If that
works, the money is on you have the wrong driver configured; switch to
pdflatex... or switch to pdflatex again :-) to make sure it happens...

Obviously I can easily generate EPS figures if that helps you or other people.

Did you also have problems with the single figure in paper-seb-main.tex ?

best,

Harold
---
Prof. Harold Thimbleby PhD FLSW FRCPE HonFRSA HonFRCP
See Change Fellow in Digital Health
Fix IT - see https://tinyurl.com/3hkrazdp
Web site - http://harold.thimbleby.net
